version: '3'
services:
  apache_1:
    build: ./apache_1
    container_name: apache_1
    ports:
      - 22000:80

  apache_2:
    build: ./apache_2
    container_name: apache_2
    ports:
      - 21000:80
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - 8080:80


